# Generated by Django 2.0.3 on 2019-10-01 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20190930_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topping',
            name='size',
            field=models.CharField(max_length=64),
        ),
    ]
