# Generated by Django 2.0.3 on 2019-10-05 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20191001_0928'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Item',
            new_name='Items',
        ),
        migrations.RenameModel(
            old_name='Topping',
            new_name='Toppings',
        ),
    ]
