# Generated by Django 2.0.3 on 2019-11-06 00:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20191005_1708'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Items')),
                ('toppings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Toppings')),
            ],
        ),
    ]
