# Generated by Django 2.0.3 on 2019-11-09 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_orders'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='toppings',
        ),
    ]
